### ISSUE TITLE
Umbrella Issue: API Refactor

### ISSUE THREAD

**Issue by Iron-Ham** [apollographql/apollo-ios-pagination#6]
Ref: https://github.com/apollographql/apollo-ios/pull/3007#pullrequestreview-1552704628 

```[tasklist]
### Tasks
- [ ] Result Handler should be within the constructor of the watcher, not the strategy. 
- [ ] Initial Query Construction: We should encapsulate initial query + pagination within a new `PaginatedQueryProvider`, which should replace the `NextPageStrategy`
- [ ] PaginationStrategy: Should be refactored to favor extensions 
- [ ] Page Data Merging & Data Transformation: Passthrough should be the default
- [ ] (Stretch) Thread Safety: watchers array should be atomic
```

**Comment by Iron-Ham** [comment]
I played around with a much simpler alternative, but unfortunately this won't work for use cases where you need a generic/erased `Watcher`/`Pager` (as we do at GitHub): 

```swift

public protocol PageInfo: Hashable {
    var hasNext: Bool { get }
}

public enum PaginationError: Error {
    case fetchingNextPageBeforeInitialPageLoaded
    case pageLoadError(any PageInfo, underlyingError: Error)
}

/// Handles pagination in the queue by managing multiple query watchers.
public class GraphQLQueryPager<InitialQuery: GraphQLQuery, PaginatedQuery: GraphQLQuery, PaginationPageInfo: PageInfo>: Pager {
    public enum PageExtractionData {
        case initial(InitialQuery.Data)
        case paginated(PaginatedQuery.Data)
    }

    typealias Output = (GraphQLResult<InitialQuery.Data>, [GraphQLResult<PaginatedQuery.Data>])

    private let client: any ApolloClientProtocol
    private var firstPageWatcher: GraphQLQueryWatcher<InitialQuery>?
    private var nextPageWatchers: [GraphQLQueryWatcher<PaginatedQuery>] = []
    private let initialQuery: InitialQuery
    private let nextPageResolver: (PaginationPageInfo) -> PaginatedQuery?
    private let extractPageInfo: (PageExtractionData) -> PaginationPageInfo
    private var currentPageInfo: PaginationPageInfo?

    /// Designated initalizer
    /// - Parameters:
    ///   - client: the Apollo client
    ///   - callbackQueue: The `DispatchQueue` that results are returned on.
    ///   - strategy: The `PaginationStrategy` that this watcher employs.
    ///   - initialQuery: The `Query` that is being watched.
    public init(
        client: ApolloClientProtocol,
        initialQuery: InitialQuery,
        extractPageInfo: @escaping (PageExtractionData) -> PaginationPageInfo,
        nextPageResolver: @escaping (PaginationPageInfo) -> PaginatedQuery
    ) {
        self.client = client
        self.initialQuery = initialQuery
        self.extractPageInfo = extractPageInfo
        self.nextPageResolver = nextPageResolver
    }

    public var canLoadNext: Bool { currentPageInfo?.hasNext ?? false }

    private var initialPageResult: GraphQLResult<InitialQuery.Data>?
    private var latest: Output? {
        guard let initialPageResult else { return nil }
        return (initialPageResult, pageOrder.compactMap({ pageMap[$0] }))
    }

    /// Array of page info used to fetch next pages. Maintains an order of values used to fetch each page in a connection.
    private var pageOrder = [PaginationPageInfo]()

    /// Maps each page info to latest results from internal watchers.
    private var pageMap = [PaginationPageInfo: GraphQLResult<PaginatedQuery.Data>]()

    // Stores a reference to callbacks to call when any page's data has been updated, or on error.
    private struct Subscription {
        let onUpdate: (GraphQLResult<InitialQuery.Data>, [GraphQLResult<PaginatedQuery.Data>]) -> Void
        let onError: (Error) -> Void
    }
    private var subscribers = [UUID: Subscription]()

    // MARK: - Public API

    /// Subscribes to updates
    /// - Parameters:
    ///   - onUpdate: Called whenever any new data comes in, whether from the cache or from a fetch.
    ///   - onError: Called whenever an error occurs from pagination.
    /// - Returns: A subscription token, used to unsubuscribe from updates.
    @discardableResult public func subscribe(
        onUpdate: @escaping (GraphQLResult<InitialQuery.Data>, [GraphQLResult<PaginatedQuery.Data>]) -> Void,
        onError: @escaping (Error) -> Void
    ) -> UUID {
        let uuid = UUID()
        subscribers[uuid] = Subscription(onUpdate: onUpdate, onError: onError)
        return uuid
    }

    /// Unsubscribes a subscriber from further updates.
    /// - Parameter token: Subscription token generated upon subscribing.
    public func unsubscribe(_ token: UUID) {
        subscribers.removeValue(forKey: token)
    }

    /// Loads the first page of results.
    public func fetch() {
        if firstPageWatcher == nil {
            self.firstPageWatcher = GraphQLQueryWatcher(
                client: client,
                query: initialQuery,
                resultHandler: { [weak self] result in
                    guard let self else { return }
                    switch result {
                    case .success(let data):
                        if case .server = data.source {
                            self.currentPageInfo = self.extractPageInfo(.initial(data.data!))
                        }
                        self.initialPageResult = data
                        for (_, subscriber) in subscribers {
                            self.latest.flatMap { subscriber.onUpdate($0.0, $0.1) }
                        }
                    case .failure(let error):
                        for (_, subscriber) in subscribers {
                            subscriber.onError(error)
                        }
                    }
                }
            )
        } else {
            assertionFailure("Did you call fetch() twice? Use GraphQLQueryPager.refetch() to fetch new data after the first page instead.")
        }
        firstPageWatcher?.refetch()
    }

    /// Loads the next page, based on the latest page info.
    public func loadMore() throws {
        if let currentPageInfo, let nextPageQuery = nextPageResolver(currentPageInfo) {
            pageOrder.append(currentPageInfo)
            let watcher = GraphQLQueryWatcher(client: client, query: nextPageQuery) { [weak self] result in
                guard let self else { return }
                switch result {
                case .success(let data):
                    if case .server = data.source {
                        self.currentPageInfo = self.extractPageInfo(.paginated(data.data!))
                    }

                    self.pageMap[currentPageInfo] = data

                    guard let initialPageResult else {
                        for (_, subscriber) in subscribers {
                            subscriber.onError(PaginationError.fetchingNextPageBeforeInitialPageLoaded)
                        }
                        return
                    }

                    for (_, subscriber) in subscribers {
                        self.latest.flatMap { subscriber.onUpdate($0.0, $0.1) }
                    }
                case .failure(let error):
                    for (_, subscriber) in subscribers {
                        subscriber.onError(error)
                    }
                }
            }
            nextPageWatchers.append(watcher)
            watcher.refetch()
        } else {
            throw PaginationError.fetchingNextPageBeforeInitialPageLoaded
        }
    }

    /// Reloads all data, starting at the first query, resetting pagination state.
    public func refresh() {
        for watcher in nextPageWatchers {
            watcher.cancel()
        }
        pageMap = [:]
        pageOrder = []
        initialPageResult = nil
        nextPageWatchers = []
        currentPageInfo = nil
        // TODO: don't reset things until fetch has completed
        // requires implementing a callback or async/await for network requests
        firstPageWatcher?.refetch()
    }

    /// Cancel any in progress fetching operations and unsubscribe from the store.
    public func cancel() {
        firstPageWatcher?.cancel()
        nextPageWatchers.forEach { $0.cancel() }
    }

    deinit {
        firstPageWatcher?.cancel()
        nextPageWatchers.forEach { $0.cancel() }
    }
}

```
